ARG NODE_BASE_IMAGE
FROM $NODE_BASE_IMAGE

WORKDIR /app
ONBUILD COPY --from=builder . .

ONBUILD ENV PATH /app/node_modules/.bin:$PATH

CMD nodemon --watch 'src/**/*.ts' --exec 'ts-node' src/index.ts
